FROM python:3.10
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline.py .
COPY config.py .
COPY data.py .
COPY models.py .
COPY training.py .
COPY mlflow_logging.py .

